name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror GitHub → GitLab
        run: |
          git clone --mirror https://github.com/arsLan4k1390/Cherrygram.git
          cd Cherrygram.git
          git remote set-url --push origin https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/arsLan4k1390/Cherrygram.git
          git push --mirror
